
CHAMPION_TO_ROLES = {
    "Aatrox": ["TOP"],
    "Ahri": ["MID"],
    "Akali": ["TOP", "MID"],
    "Akshan": ["MID", "ADC"],
    "Alistar": ["SUPPORT"],
    "Amumu": ["JUNGLE"],
    "Anivia": ["MID"],
    "Annie": ["MID", "SUPPORT"],
    "Aphelios": ["ADC"],
    "Ashe": ["ADC"],
    "Aurelion Sol": ["MID"],
    "Aurora": ["TOP", "MID"],
    "Azir": ["MID"],
    "Bard": ["SUPPORT"],
    "Bel'Veth": ["JUNGLE"],
    "Blitzcrank": ["SUPPORT"],
    "Brand": ["MID", "SUPPORT", "JUNGLE"],
    "Braum": ["SUPPORT", "TOP"],
    "Briar": ["JUNGLE", "TOP"],
    "Caitlyn": ["ADC"],
    "Camille": ["TOP"],
    "Cassiopeia": ["MID"],
    "Cho'Gath": ["TOP", "MID"],
    "Corki": ["MID", "ADC"],
    "Darius": ["TOP"],
    "Diana": ["MID", "JUNGLE"],
    "Dr. Mundo": ["TOP", "JUNGLE"],
    "Draven": ["ADC"],
    "Ekko": ["JUNGLE", "MID"],
    "Elise": ["JUNGLE"],
    "Evelynn": ["JUNGLE"],
    "Ezreal": ["ADC"],
    "Fiddlesticks": ["JUNGLE", "SUPPORT", "MID"],
    "Fiora": ["TOP"],
    "Fizz": ["MID", "TOP"],
    "Galio": ["MID", "SUPPORT", "TOP"],
    "Gangplank": ["TOP", "MID"],
    "Garen": ["TOP"],
    "Gnar": ["TOP"],
    "Gragas": ["TOP", "JUNGLE", "MID"], 
    "Graves": ["JUNGLE"],
    "Gwen": ["TOP"],
    "Hecarim": ["JUNGLE"],
    "Heimerdinger": ["MID", "TOP", "SUPPORT"],
    "Hwei": ["MID", "ADC"],  # flex pending clarificación
    "Illaoi": ["TOP"],
    "Irelia": ["TOP", "MID"],
    "Ivern": ["JUNGLE"],
    "Janna": ["SUPPORT"],
    "Jarvan IV": ["JUNGLE", "TOP"],
    "Jax": ["TOP", "JUNGLE"],
    "Jayce": ["TOP", "MID", "ADC"],
    "Jhin": ["ADC"],
    "Jinx": ["ADC"],
    "Kai'Sa": ["ADC"],
    "Kalista": ["ADC"],
    "Karma": [ "SUPPORT","TOP", "MID" ],
    "Karthus": ["JUNGLE", "MID"],
    "Kassadin": ["MID"],
    "Katarina": ["MID"],
    "Kayle": ["TOP", "MID"],
    "Kayn": ["JUNGLE"],
    "K'Sante": ["TOP"],
    "Kennen": ["TOP", "MID"],
    "Kha'Zix": ["JUNGLE"],
    "Kindred": ["JUNGLE"],
    "Kled": ["TOP"],
    "Kog'Maw": ["ADC"],
    "Leblanc": ["MID"],
    "Lee Sin": ["JUNGLE"],
    "Leona": ["SUPPORT"],
    "Lillia": ["JUNGLE"],
    "Lissandra": ["MID"],
    "Lucian": ["ADC"],
    "Lulu": ["SUPPORT"],
    "Lux": ["MID", "SUPPORT"],
    "Malphite": ["TOP", "JUNGLE"],
    "Malzahar": ["MID"],
    "Maokai": [ "JUNGLE", "TOP", "SUPPORT" ],
    "Master Yi": ["JUNGLE"],
    "Mel": ["MID", "SUPPORT"],  # champion #170, pero posterior a Ambessa :contentReference[oaicite:1]{index=1}
    "Milio": ["SUPPORT"],
    "Miss Fortune": ["ADC"],
    "Mordekaiser": ["TOP", "MID"],
    "Morgana": ["SUPPORT", "MID"],
    "Naafiri": ["JUNGLE"],
    "Nami": ["SUPPORT"],
    "Nasus": ["TOP"],
    "Nautilus": ["SUPPORT", "TOP"],
    "Neeko": [ "SUPPORT", "TOP", "MID" ],
    "Nilah": ["ADC"],
    "Nocturne": ["JUNGLE"],
    "Nunu & Willump": ["JUNGLE", "MID", "SUPPORT"],
    "Olaf": ["JUNGLE", "TOP"],
    "Orianna": ["MID"],
    "Ornn": ["TOP"],
    "Pantheon": ["JUNGLE", "TOP", "MID"],
    "Poppy": ["TOP", "JUNGLE", "SUPPORT"],
    "Pyke": ["SUPPORT", "JUNGLE"],
    "Qiyana": ["MID"],
    "Quinn": ["TOP"],
    "Rakan": ["SUPPORT"],
    "Rammus": ["JUNGLE"],
    "Renekton": ["TOP"],
    "Rell": ["SUPPORT", "TOP"],
    "Rengar": ["JUNGLE", "ADC"],
    "Riven": ["TOP"],
    "Rumble": ["TOP", "JUNGLE", "MID"],
    "Ryze": ["MID" , "TOP"],
    "Samira": ["ADC"],
    "Sejuani": ["JUNGLE"],
    "Senna": ["SUPPORT", "ADC"],
    "Seraphine": ["SUPPORT", "ADC", "MID"],
    "Sett": ["TOP", "JUNGLE"],
    "Shaco": ["JUNGLE"],
    "Shen": ["TOP", "SUPPORT"],
    "Shyvana": ["JUNGLE", "TOP"],
    "Singed": ["TOP"],
    "Sion": ["TOP"],
    "Sivir": ["ADC"],
    "Skarner": ["JUNGLE"],
    "Smolder": ["ADC", "MID"],
    "Sona": ["SUPPORT"],
    "Soraka": ["SUPPORT"],
    "Swain": ["SUPPORT", "MID", "TOP"],
    "Sylas": ["MID", "JUNGLE"],
    "Syndra": ["MID"],
    "Tahm Kench": ["SUPPORT", "TOP"],
    "Taliyah": ["MID", "JUNGLE"],
    "Talon": ["MID"],
    "Taric": ["SUPPORT", "TOP"],
    "Teemo": ["TOP", "JUNGLE", "MID"],
    "Thresh": ["SUPPORT"],
    "Tristana": ["ADC", "MID"],
    "Trundle": ["TOP", "JUNGLE"],
    "Tryndamere": ["TOP"],
    "Twisted Fate": ["MID", "JUNGLE"],
    "Twitch": ["ADC"],
    "Udyr": ["JUNGLE"],
    "Urgot": ["TOP"],
    "Varus": ["ADC"],
    "Vayne": ["ADC", "TOP"],
    "Veigar": ["MID", "SUPPORT"],
    "Vex": ["MID", "SUPPORT"],
    "Vi": ["JUNGLE", "TOP"],
    "Viego": ["JUNGLE"],
    "Viktor": ["MID"],
    "Vladimir": ["TOP", "MID"],
    "Volibear": ["JUNGLE", "TOP"],
    "Warwick": ["JUNGLE", "TOP"],
    "Wukong": ["TOP", "JUNGLE"],
    "Xayah": ["ADC"],
    "Xerath": ["MID"],
    "Xin Zhao": ["JUNGLE"],
    "Yasuo": ["MID", "TOP", "ADC"],
    "Yone": ["MID", "TOP", "ADC"],
    "Yuumi": ["SUPPORT"],
    "Zed": ["MID", "TOP"],
    "Zeri": ["ADC"],
    "Ziggs": ["MID"],
    "Zilean": ["SUPPORT", "MID", "TOP"],
    "Zoe": ["MID"],
    "Zyra": ["JUNGLE", "SUPPORT"],
    
    "Ambessa": ["TOP", "JUNGLE", "MID"],  # flex alta :contentReference[oaicite:2]{index=2}
}


TEAM_TRICODES = {
    "FLY": "FlyQuest",
    "G2": "G2 Esports",
    "CFO": "CTBC Flying Oyster",
    "BLG": "Bilibili Gaming",
    "GENG": "Gen.G",
    "T1": "T1",
    "MKOI": "MOVISTAR KOI",
    "FUR": "FURIA",
    "GAM": "GAM Esports",
    "AL": "Anyone's Legend",
}


QUEUE_ID_TO_NAME: dict[int, str] = {
    400: "Normal Draft",
    420: "Clasificatoria Solo/Duo",
    430: "Normal Blind",
    440: "Clasificatoria Flex",
    450: "ARAM",
    700: "Clash",
    900: "URF",
    1700: "Arena",
    1300: "Nexus Blitz",
    1090: "TFT Normal",
    1100: "TFT Ranked",
    0: "Personalizada",
    830: "Tutorial",
    840: "Bots",
}

ROLE_ORDER = ["TOP", "JUNGLE", "MID", "ADC", "SUPPORT"]